# EigenValue Dan EigenVector
Nilai Eigen dan Vektor Eigen adalah konsep fundamental dalam teori struktur matriks persegi. Mereka memainkan peran penting dalam aplikasi aljabar linear

Vektor Eigen dari sebuah matriks persegi A adalah vektor non-nol v dalam R^n sehingga ketika A dikalikan dengan v, hasilnya adalah kelipatan skalar dari v

Dalam kata lain, jika kita memiliki matriks A dan vektor v, maka vektor v disebut vektor Eigen dari A jika memenuhi persamaan berikut:
A × v = λ × v

## Menghitung EigenValue dan EigenVector Menggunakan numpy

In [1]:
import numpy as np
from numpy import linalg as LA

a = np.array([[1,4],[2,3]])
print(a)
eigenvalues, eigenvectors = LA.eig(a)
print(eigenvalues)
print(eigenvectors.round())

[[1 4]
 [2 3]]
[-1.  5.]
[[-1. -1.]
 [ 0. -1.]]


## Implementasi dari eigenvalue dan eigenvector dari analisis data
### Konsep Eigenvalue dan Eigenvector

#### Definisi
- **Eigenvalue (Nilai Eigen):** Nilai skalar λ yang memenuhi persamaan Av=λv, di mana A, adalah matriks dan V adalah eigenvector yang sesuai.
- **Eigenvector (Vektor Eigen):** Vektor V yang tidak berubah arah setelah dikalikan dengan matriks A, 
hanya skala atau panjangnya saja yang berubah sesuai dengan eigenvalue λ.

#### Persamaan Karakteristik
Untuk menemukan eigenvalue, kita menyelesaikan persamaan determinan berikut: det(A−λI)=0
di mana I adalah matriks identitas dengan ukuran yang sama dengan A.


### Contoh Hitungan Eigenvalue dan Eigenvector dengan NumPy

#### Matriks 2x2
Misalkan  A = 
\begin{bmatrix} 
4 & 1 \\ 
2 & 3 
\end{bmatrix} .

#### Matriks 3x3
Misalkan  A = 
\begin{bmatrix} 
6 & 2 & 1 \\ 
2 & 3 & 1 \\ 1 & 1 & 1 
\end{bmatrix} .

In [4]:
# Import libraries
import numpy as np

# Matriks 2x2
A_2x2 = np.array([[4, 1],
                  [2, 3]])

# Hitung eigenvalue dan eigenvector
eigenvalues_2x2, eigenvectors_2x2 = np.linalg.eig(A_2x2)

print("Matriks 2x2:")
print(A_2x2)
print("Eigenvalues:\n", eigenvalues_2x2)
print("Eigenvectors:\n", eigenvectors_2x2)
print("\n")

# Matriks 3x3
A_3x3 = np.array([[6, 2, 1],
                  [2, 3, 1],
                  [1, 1, 1]])

# Hitung eigenvalue dan eigenvector
eigenvalues_3x3, eigenvectors_3x3 = np.linalg.eig(A_3x3)

print("Matriks 3x3:")
print(A_3x3)
print("Eigenvalues: \n", eigenvalues_3x3)
print("Eigenvectors:\n", eigenvectors_3x3)

Matriks 2x2:
[[4 1]
 [2 3]]
Eigenvalues:
 [5. 2.]
Eigenvectors:
 [[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


Matriks 3x3:
[[6 2 1]
 [2 3 1]
 [1 1 1]]
Eigenvalues: 
 [7.28799214 2.13307448 0.57893339]
Eigenvectors:
 [[ 0.86643225  0.49742503 -0.0431682 ]
 [ 0.45305757 -0.8195891  -0.35073145]
 [ 0.20984279 -0.28432735  0.9354806 ]]


### Penjelasan Output
- **Eigenvalues**: Nilai-nilai ini adalah skalar yang menunjukkan seberapa besar vektor eigen (eigenvector) akan diperbesar atau diperkecil ketika matriks A diaplikasikan padanya.
- **Eigenvectors**: Vektor-vektor ini menunjukkan arah di mana transformasi matriks A hanya mengubah skala, bukan arah. Setiap kolom dari matriks hasil adalah eigenvector yang sesuai dengan eigenvalue pada posisi yang sama.