# Matrix Invers
Dalam matematika, matriks invers adalah matriks yang ketika dikalikan dengan matriks aslinya menghasilkan matriks identitas.
Misal kita memiliki Matriks A, Jika ada sebuah matriks B sedemikian rupa, sehingga A x B = B x A = I, dimana I adalah Matriks Identitas, Maka B disebut Invers dari A, yang di lambangkan A-1,

## Mencari matrix invers menggunakan eliminasi gauss
Metode Gauss-Jordan merupakan salah satu varian dari eliminasi Gaussian yang dilakukan dengan cara operasi reduksi baris untuk mencari invers suatu matriks.

Misal kita mau mencari invers dari sebuah matriks 3x3
A = 
\begin{bmatrix}
1 & 2 & 3\\ 
0 & 1 & 4\\ 
5 & 6 & 0
\end{bmatrix}

I = 
\begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1\\
\end{bmatrix}

Setelah itu kita menggunakan eliminasi gaus jordan

\begin{bmatrix}
1 & 2 & 3 | 1 & 0 & 0\\
0 & 1 & 4 | 0 & 1 & 0\\
5 & 6 & 0 | 0 & 0 & 1\\
\end{bmatrix}

Sekarang kita kurangkan baris ketiga dengan 5x baris pertama

\begin{bmatrix}
1 & 2 & 3 | 1 & 0 & 0\\
0 & 1 & 4 | 0 & 1 & 0\\
0 & -4 & -15 | -5 & 0 & 1\\
\end{bmatrix}

Dari matriks diatas, kita tambahkan baris ke 3 dengan 4kali baris ke dua 

\begin{bmatrix}
1 & 2 & 3 | 1 & 0 & 0\\
0 & 1 & 4 | 0 & 1 & 0\\
0 & 0 & 1 | -5 & 4 & 1\\
\end{bmatrix}

selanjutnya kita kurangkan baris kedua dengan 4x baris ketiga, dan kita kurangkan juga baris pertama dengan 3x baris ketiga
\begin{bmatrix}
1 & 2 & 0 | 16 & -12 & -3\\
0 & 1 & 0 | 20 & -15 & -4\\
0 & 0 & 1 | -5 & 4 & 1\\
\end{bmatrix}

langkah terakhir kita kurangkan baris pertama dengan 2x baris kedua
\begin{bmatrix}
1 & 0 & 0 | -24 & 18 & 5\\
0 & 1 & 0 | 20 & -15 & -4\\
0 & 0 & 1 | -5 & 4 & 1\\
\end{bmatrix}

Maka invers dari matriks A adalah : 
\begin{bmatrix}
-24 & 18 & 5\\
20 & -15 & -4\\
-5 & 4 & 1\\
\end{bmatrix}

## Program untuk Mencari matrix invers menggunakan eliminasi gauss

In [8]:
import numpy as np

# Membuat Matriks 
A = np.array([(1,2,3),
             (0,1,4),
             (5,6,0)])
I = np.array([(1,0,0),
              (0,1,0),
              (0,0,1)])
print("Matriks A : \n")
print(A)
print("\n Matriks Identitas : \n")
print(I)

Matriks A : 

[[1 2 3]
 [0 1 4]
 [5 6 0]]

 Matriks Identitas : 

[[1 0 0]
 [0 1 0]
 [0 0 1]]


## Gunakan eliminasi Gauss

In [ ]:
EG = np.array([(1,2,3,1,0,0),
             (0,1,4,0,1,0),
             (5,6,0,0,0,1)])
print(EG)

## Fungsi RowAdd RowSwap Dan RowScale

In [12]:
def RowSwap(A,k,l):
# =============================================================================
#     A adalah sebuah NumPy array.  RowSwap akan menghasilkan duplicate dari 
#     array dengan baris k dan l di tukar
# =============================================================================
    m = A.shape[0]  # m adalah nomor baris di A
    n = A.shape[1]  # n adalah nomor kolom di A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A adalah sebuah NumPy array.  RowScale akan menghasilkan duplicate dari 
#     array dengan baris k di kali dengan skalar bukan 0
# =============================================================================
    m = A.shape[0]  # m adalah nomor baris di A
    n = A.shape[1]  # n adalah nomor kolom di A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A adalah sebuah NumPy array.  RowAdd akan menghasilkan duplicate dari 
#     array dengan baris k akan di kali dengan 'scale' bukan 0. lalu nilai
#     baris l akan di tambah dengan nilai baris k yang sudah dikalikan  
# =============================================================================
    m = A.shape[0]  # m adalah nomor baris di A
    n = A.shape[1]  # n adalah nomor kolom di A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

## Sekarang kita kurangkan baris ketiga dengan 5x baris pertama

In [14]:
RA = np.array([(1,2,3,1,0,0),
             (0,1,4,0,1,0),
             (5,6,0,0,0,1)])

k = 0
l = 2
scale = -5

result = RowAdd(RA, k, l, scale)
print("Matriks awal:")
print(RA)
print("\nHasil:")
print(result)

Matriks awal:
[[1 2 3 1 0 0]
 [0 1 4 0 1 0]
 [5 6 0 0 0 1]]

Matriks setelah baris ketiga dikurang dengan 5x baris pertama:
[[  1.   2.   3.   1.   0.   0.]
 [  0.   1.   4.   0.   1.   0.]
 [  0.  -4. -15.  -5.   0.   1.]]


## Dari matriks diatas, kita tambahkan baris ke 3 dengan 4kali baris ke dua

In [18]:
RA2 = np.array([(1,2,3,1,0,0),
             (0,1,4,0,1,0),
             (0,-4,-15,-5,0,1)])
k = 1
l = 2
scale = 4

result = RowAdd(RA2, k, l, scale)
print("Matriks awal:")
print(RA2)
print("\nHasil:")
print(result)

Matriks awal:
[[  1   2   3   1   0   0]
 [  0   1   4   0   1   0]
 [  0  -4 -15  -5   0   1]]

Matriks setelah baris ketiga dikurang dengan 5x baris pertama:
[[ 1.  2.  3.  1.  0.  0.]
 [ 0.  1.  4.  0.  1.  0.]
 [ 0.  0.  1. -5.  4.  1.]]


## selanjutnya kita kurangkan baris kedua dengan 4x baris ketiga,

In [21]:
RA3 = np.array([(1,2,3,1,0,0),
             (0,1,4,0,1,0),
             (0,0,1,-5,4,1)])

k = 2
l = 1
scale = -4

result = RowAdd(RA3, k, l, scale)
print("Matriks awal:")
print(RA3)
print("\nHasil :")
print(result)

Matriks awal:
[[ 1  2  3  1  0  0]
 [ 0  1  4  0  1  0]
 [ 0  0  1 -5  4  1]]

Matriks setelah baris ketiga dikurang dengan 5x baris pertama:
[[  1.   2.   3.   1.   0.   0.]
 [  0.   1.   0.  20. -15.  -4.]
 [  0.   0.   1.  -5.   4.   1.]]


## kita kurangkan juga baris pertama dengan 3x baris ketiga

In [22]:
RA4 = np.array([(1,2,3,1,0,0),
             (0,1,0,20,-15,-4),
             (0,0,1,-5,4,1)])
k = 2
l = 0
scale = -3

result = RowAdd(RA4, k, l, scale)
print("Matriks awal:")
print(RA4)
print("\nHasil :")
print(result)


Matriks awal:
[[  1   2   3   1   0   0]
 [  0   1   0  20 -15  -4]
 [  0   0   1  -5   4   1]]

Hasil :
[[  1.   2.   0.  16. -12.  -3.]
 [  0.   1.   0.  20. -15.  -4.]
 [  0.   0.   1.  -5.   4.   1.]]


## langkah terakhir kita kurangkan baris pertama dengan 2x baris kedua

In [24]:
RA5 = np.array([(1,2,0,16,-12,-3),
             (0,1,0,20,-15,-4),
             (0,0,1,-5,4,1)])
k = 1
l = 0
scale = -2

result = RowAdd(RA5, k, l, scale)
print("Matriks awal:")
print(RA5)
print("\nHasil :")
print(result)

Matriks awal:
[[  1   2   0  16 -12  -3]
 [  0   1   0  20 -15  -4]
 [  0   0   1  -5   4   1]]

Hasil :
[[  1.   0.   0. -24.  18.   5.]
 [  0.   1.   0.  20. -15.  -4.]
 [  0.   0.   1.  -5.   4.   1.]]


Maka invers dari matriks A adalah : 
\begin{bmatrix}
-24 & 18 & 5\\
20 & -15 & -4\\
-5 & 4 & 1\\
\end{bmatrix}

## Penyelesaian sistem persamaan linear menggunakan matriks invers 
membuat soal 4persamaan 4variabel, mencari solusi menggunakan matrik invers