# Eliminasi Gaus
Eliminasi Gauss adalah algoritma yang digunakan untuk menyelesaikan sistem persamaan linear. Algoritma ini terdiri dari serangkaian operasi yang dilakukan pada matriks koefisien dari sistem persamaan tersebut.

Ada tiga jenis operasi baris dasar yang dapat dilakukan pada baris matriks tersebut:

1. Menukar posisi dua baris.

2. Mengalikan suatu baris dengan skalar bukan nol .

3. Menambahkan suatu baris dengan suatu kelipatan dari baris yang lain.

Operasi-operasi ini tidak mengubah kumpulan solusi. Oleh karena itu, jika tujuan seseorang adalah untuk menyelesaikan sistem persamaan linear, penggunaan operasi baris ini dapat membuat masalah menjadi lebih mudah

### Row Swap

Row swap adalah operasi dasar pada matriks yang melibatkan pertukaran dua baris. Dalam operasi ini, dua baris pada matriks ditukar posisinya. Operasi row swap sering digunakan dalam proses Eliminasi Gauss, 

Semisal Kita Memiliki Matrix berikut

In [2]:
import numpy as np
A=np.array([[8,9,1,19],
            [1,2,3,9],
            [2,1,1,5]])
print(A)

[[ 8  9  1 19]
 [ 1  2  3  9]
 [ 2  1  1  5]]


Dan kita ingin menukar baris pertama dengan baris kedua, maka setelah operasi row swap, matriks akan menjadi:

In [15]:
def RowSwap(A,k,l):
# =============================================================================
#     A adalah sebuah NumPy array.  RowSwap akan menghasilkan duplicate dari 
#     array dengan baris k dan l di tukar
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

RSW=np.array([[8,9,1,19],
              [1,2,3,9],
              [2,1,1,5]])

k = 0
l = 1

# Memanggil fungsi RowSwap dan menampilkan outputnya
result = RowSwap(RSW, k, 1)
print("Matriks awal:")
print(RSW)
print("\nMatriks setelah RowSwap:")
print(result)


Matriks awal:
[[ 8  9  1 19]
 [ 1  2  3  9]
 [ 2  1  1  5]]

Matriks setelah RowSwap:
[[ 1.  2.  3.  9.]
 [ 8.  9.  1. 19.]
 [ 2.  1.  1.  5.]]


### Row Scale

Row scale adalah operasi dasar pada matriks yang melibatkan pengalihan (skalasi) satu baris dengan suatu skalar (bilangan konstan). Dalam operasi ini, setiap elemen pada baris tertentu dikalikan dengan skalar tersebut.

Misalnya, jika kita memiliki matriks berikut:

In [11]:
RSC=np.array([[6,9,1],
              [1,2,3],
              [2,6,4]])
print(A)

[[6 9 1]
 [1 2 3]
 [2 6 4]]


Dan kita ingin mengalikan baris pertama dengan 2, maka setelah operasi row scale, matriks akan menjadi:

In [4]:

def RowScale(A,k,scale):
# =============================================================================
#     RSC adalah sebuah NumPy array.  RowScale akan menghasilkan duplicate dari 
#     array dengan baris k di kali dengan skalar bukan 0
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

RSC=np.array([[6,9,1],
              [1,2,3],
              [2,6,4]])

k = 1
scale = 2

# Memanggil fungsi RowScale dan menampilkan outputnya
result = RowScale(RSC, k, scale)
print("Matriks awal:")
print(RSC)
print("\nMatriks setelah RowScale:")
print(result)


Matriks awal:
[[6 9 1]
 [1 2 3]
 [2 6 4]]

Matriks setelah RowScale:
[[6. 9. 1.]
 [2. 4. 6.]
 [2. 6. 4.]]


### Row Add

Row add adalah operasi dasar pada matriks yang melibatkan penambahan hasil perkalian satu baris dengan suatu skalar (bilangan konstan) terhadap baris lainnya. Dalam operasi ini, setiap elemen pada suatu baris akan ditambahkan dengan hasil perkalian skalar tersebut terhadap elemen pada baris lain.

Misalnya, jika kita memiliki matriks berikut:

In [18]:
RA=np.array([[8,9,1,20],
             [1,2,13,9],
             [2,11,3,5]])
print(RA)

[[ 8  9  1 19]
 [ 1  2  3  9]
 [ 2  1  1  5]]


Dan kita ingin menambahkan dua kali baris pertama ke baris kedua, maka setelah operasi row add, matriks akan menjadi:

In [19]:
def RowAdd(A,k,l,scale):
# =============================================================================
#     A adalah sebuah NumPy array.  RowAddp akan menghasilkan duplicate dari 
#     array dengan baris k akan di kali dengan scalar bukan 0. lalu baris nilai
#     baris l akan di tambah dengan nilai baris k yang sudah dikalikan  
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

RA=np.array([[8,9,1,20],
             [1,2,13,9],
             [2,11,3,5]])

k = 0
l = 1
scale = 2

# Memanggil fungsi RowAdd dan menampilkan outputnya
result = RowAdd(RA, k, l, scale)
print("Matriks awal:")
print(RA)
print("\nMatriks setelah RowAdd:")
print(result)

Matriks awal:
[[ 8  9  1 20]
 [ 1  2 13  9]
 [ 2 11  3  5]]

Matriks setelah RowAdd:
[[ 8.  9.  1. 20.]
 [17. 20. 15. 49.]
 [ 2. 11.  3.  5.]]


Hasil Dari Sistem Persamaan Berikut :

$$
    8x_1 + 9x_2 + x_3 = 19\\
    x_1  + 2x_2 + 3x_3 = 9\\
    2x_1 + x_2  + x_3 = 5
$$

Hasil Setelah di bulatkan : 

$$
    x_1 + 2x_2 + 3x_3 = 9\\
    x_2 + 3x_3 = 8\\
    x_3 = 2
$$
