# Aljabar Matrix
Aljabar matriks adalah cabang aljabar yang mempelajari matriks, yaitu susunan bilangan-bilangan (elemen) dalam baris dan kolom. Matriks dapat digunakan untuk merepresentasikan sistem persamaan linear, transformasi linier, dan berbagai konsep matematika lainnya.

Berikut adalah contoh dari Aljabar Matriks :

In [1]:
import numpy as np

A = np.random.randint(10,size=(3,3))
print(A)

[[6 3 0]
 [5 4 6]
 [5 1 8]]


## Menghitung matrix menggunakan Program

### Cara menentukan Matrix Secara Manual Menggunakan Program python

1. kita memanggil library numpy menggunakan syntax
[import numpy]
import gunanya untuk kita memanggil file lain dalam satu modul,
numpy adalah sebuah library yang bisa di panggil 

2. kita membuat matrix secara manual menggunakan syntax
[ A = numpy.array([[3,0,4],[-1,-2,-1]]) ]
kita membuat variable "A", dengan isi numpy.array
numpy adalah library yang sudah kita panggil tadi, dan array kegunaannya untuk memudahkan operasi komputasi tipe data numerik seperti penjumlahan, pengurangan, perkalian, pangkat, dan operasi lainnya yang bisa diterapkan pada vektor atau matrix
dan kita memberi angka untuk kolom dan baris pada matrix

In [2]:
import numpy

A = numpy.array([[3,0,4],[-1,-2,-1]])
print(A)

[[ 3  0  4]
 [-1 -2 -1]]


### Cara Menentukan Matrix Secara Random menggunakan progam python
1. kita memanggil numpy dan random menggunakan syntax 
[import numpy] & [import Random]
import gunanya untuk kita memanggil file lain dalam satu modul,
numpy dan random adalah sebuah library yang bisa di panggil 

2. kita membuat matrix menggunakan syntax
[ "A = numpy.random.randint(10, size=(3,3))" ]
Kita membuat Variabel "A", dengan isi "numpy.random.ranint(10, size=(3,0)),
disini kegunaan dari randint sendiri adalah untuk mengacak angka, dan 10 adalah batas dari acak angka randint, 
size=(3,3) adalah ukuran kolom baris sebuah matrix

In [3]:
import numpy as np
import random

A = np.random.randint(10,size=(3,3))
print(A)

[[2 9 4]
 [8 7 0]
 [5 4 0]]


### Cara Mengubah matrix menjadi matrix transpose menggunakan program python
1. Menentukan Matrix mana yang ingin di transpose, dan beri syntax
[A.transpose()]
Syntax "transpose()" digunakan untuk menghasilkan transpos dari matriks A. Transpos suatu matriks adalah operasi yang mengubah baris matriks menjadi kolom dan sebaliknya. Dengan kata lain, elemen pada baris ke-i dan kolom ke-j dari matriks asli akan menjadi elemen pada baris ke-j dan kolom ke-i dalam matriks transpos.

In [4]:
import numpy as np
import random

A = np.random.randint(10,size=(3,3))
A_T = A.transpose()
print("Matrix A")
print(A)
print("Matrix A yang sudah di transpose")
print(A_T)

Matrix A
[[4 2 0]
 [0 1 5]
 [7 7 7]]
Matrix A yang sudah di transpose
[[4 0 7]
 [2 1 7]
 [0 5 7]]


### Cara Mengetahui Shape Matrix Menggunakan Program Python 
1. Menentukan variable matrix mana yang ingin di ketahui shape nya, dan tambahkan syntax
[A.Shape]
Shape digunakan untuk mendapatkan tuple yang menyatakan dimensi dari array/matriks A. Dalam konteks NumPy atau library lain yang mendukung atribut shape, A.shape memberikan informasi tentang jumlah baris dan kolom 

In [5]:
import numpy as np
import random

A = np.random.randint(10,size=(3,3))
A.shape

(3, 3)


## TUGAS MATERI PERTEMUAN 3
Mengalikan Matrix Menggunakan Python

In [6]:
import numpy as np

A = np.random.randint(10, size=(3, 2))
B = np.random.randint(10, size=(2, 3))



Kumpulan_matrix = [A, B]

hasil = Kumpulan_matrix[0]

for matrix in Kumpulan_matrix[1:]:
    hasil = np.dot(hasil, matrix)

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nHasil akhir perkalian matriks:")
print(hasil)


Matrix A:
[[5 3]
 [8 6]
 [1 1]]

Matrix B:
[[1 0 0]
 [1 0 4]]

Hasil akhir perkalian matriks:
[[ 8  0 12]
 [14  0 24]
 [ 2  0  4]]
