# Aljabar Matrix
Aljabar matriks adalah cabang aljabar yang mempelajari matriks, yaitu susunan bilangan-bilangan (elemen) dalam baris dan kolom. Matriks dapat digunakan untuk merepresentasikan sistem persamaan linear, transformasi linier, dan berbagai konsep matematika lainnya.

Berikut adalah contoh dari Aljabar Matriks :

In [1]:
import numpy as np

A = np.random.randint(10,size=(3,3))
print(A)

[[9 2 5]
 [5 4 8]
 [2 2 6]]


## Menghitung matrix menggunakan Program

### Cara menentukan Matrix Secara Manual Menggunakan Program python

1. kita memanggil library numpy menggunakan syntax
[import numpy]
import gunanya untuk kita memanggil file lain dalam satu modul,
numpy adalah sebuah library yang bisa di panggil 

2. kita membuat matrix secara manual menggunakan syntax
[ A = numpy.array([[3,0,4],[-1,-2,-1]]) ]
kita membuat variable "A", dengan isi numpy.array
numpy adalah library yang sudah kita panggil tadi, dan array kegunaannya untuk memudahkan operasi komputasi tipe data numerik seperti penjumlahan, pengurangan, perkalian, pangkat, dan operasi lainnya yang bisa diterapkan pada vektor atau matrix
dan kita memberi angka untuk kolom dan baris pada matrix

In [2]:
import numpy

A = numpy.array([[3,0,4],[-1,-2,-1]])
print(A)

[[ 3  0  4]
 [-1 -2 -1]]


### Cara Menentukan Matrix Secara Random menggunakan progam python
1. kita memanggil numpy dan random menggunakan syntax 
[import numpy] & [import Random]
import gunanya untuk kita memanggil file lain dalam satu modul,
numpy dan random adalah sebuah library yang bisa di panggil 

2. kita membuat matrix menggunakan syntax
[ "A = numpy.random.randint(10, size=(3,3))" ]
Kita membuat Variabel "A", dengan isi "numpy.random.ranint(10, size=(3,0)),
disini kegunaan dari randint sendiri adalah untuk mengacak angka, dan 10 adalah batas dari acak angka randint, 
size=(3,3) adalah ukuran kolom baris sebuah matrix

In [3]:
import numpy as np
import random

A = np.random.randint(10,size=(3,3))
print(A)

[[9 6 1]
 [9 3 5]
 [5 5 3]]


### Cara Mengubah matrix menjadi matrix transpose menggunakan program python
1. Menentukan Matrix mana yang ingin di transpose, dan beri syntax
[A.transpose()]
Syntax "transpose()" digunakan untuk menghasilkan transpos dari matriks A. Transpos suatu matriks adalah operasi yang mengubah baris matriks menjadi kolom dan sebaliknya. Dengan kata lain, elemen pada baris ke-i dan kolom ke-j dari matriks asli akan menjadi elemen pada baris ke-j dan kolom ke-i dalam matriks transpos.

In [4]:
import numpy as np
import random

A = np.random.randint(10,size=(3,3))
A_T = A.transpose()
print("Matrix A")
print(A)
print("Matrix A yang sudah di transpose")
print(A_T)

Matrix A
[[9 2 9]
 [0 1 0]
 [1 6 1]]
Matrix A yang sudah di transpose
[[9 0 1]
 [2 1 6]
 [9 0 1]]


### Cara Mengetahui Shape Matrix Menggunakan Program Python 
1. Menentukan variable matrix mana yang ingin di ketahui shape nya, dan tambahkan syntax
[A.Shape]
Shape digunakan untuk mendapatkan tuple yang menyatakan dimensi dari array/matriks A. Dalam konteks NumPy atau library lain yang mendukung atribut shape, A.shape memberikan informasi tentang jumlah baris dan kolom 

In [5]:
import numpy as np
import random

A = np.random.randint(10,size=(3,3))
A.shape

(3, 3)

## Perkalian Matrix

Perkalian matriks adalah operasi matematika yang menggabungkan dua matriks untuk menghasilkan matriks baru. Untuk melakukan perkalian matriks, jumlah kolom matriks pertama harus sama dengan jumlah baris matriks kedua. Hasilnya adalah matriks baru dengan jumlah baris sama dengan matriks pertama dan jumlah kolom sama dengan matriks kedua

## Cara Kerja Perkalian Matrix

Perkalian matriks bekerja dengan menggabungkan elemen-elemen matriks pertama dan matriks kedua sesuai dengan aturan perkalian matriks. Berikut adalah langkah-langkah umum cara kerja perkalian matriks:

1. Periksa Kesesuaian: 
Pastikan jumlah kolom matriks pertama sama dengan jumlah baris matriks kedua. Jika tidak, maka perkalian matriks tidak bisa dilakukan.

2. Hitung Elemen Baru: 
Untuk setiap elemen C[i][j] dalam matriks hasil C, lakukan perkalian antara baris i dari matriks pertama dengan kolom j dari matriks kedua. Misalnya, untuk menghitung C[1][1], perkalian dilakukan antara elemen-elemen baris pertama dari matriks pertama dengan elemen-elemen kolom pertama dari matriks kedua.

3. Jumlahkan Hasil: 
Setelah melakukan perkalian, jumlahkan hasil perkalian untuk mendapatkan nilai elemen C[i][j] yang baru.

4. Ulangi Langkah 2-3: 
Lakukan langkah-langkah 2 dan 3 untuk setiap elemen matriks hasil C.

5. Hasil Akhir: 
Setelah semua elemen matriks hasil C dihitung, Anda akan mendapatkan matriks hasil yang merupakan hasil perkalian dari matriks pertama dan matriks kedua.



## Cara Mengalikan Matrix Menggunakan Program Python Secara Manual

In [6]:
listA = [
    [5,3],
    [5,2],
    [3,1]
    ]

listB = [
    [5,2,3],
    [3,6,5],
    ]
  
print("Matriks A",listA,"\n")
print("MAtriks B",listB,"\n")

print("panjang baris dan kolom")

print("Matriks A")
print(len(listA),len(listA[0]),"\n")

print("Matriks B")
print(len(listB),len(listB[0]),"\n")

# n adalah panjang baris matrix listA
n = len(listA)

# adalah panjang kolom matrix listA dan panjang baris matrix listB
m = len(listA[0])

# p adalah panjang baris matrix listB
p = len(listB[0])

hasil = []
# perulangan terjadi sebanyak panjang baris listA
for i in range(0,n):
  hasil1 = []
  # perulangan terjadi sebanyak panjang baris listB
  for j in range(0,p):
    jumlah = 0
    for k in range(0,m):
      jumlah += listA[i][k] * listB[k][j]
    hasil1.append(jumlah)
  hasil.append(hasil1)
print("hasil dari perkalian matrix")
print(hasil,"\n")

Matriks A [[5, 3], [5, 2], [3, 1]] 

MAtriks B [[5, 2, 3], [3, 6, 5]] 

panjang baris dan kolom
Matriks A
3 2 

Matriks B
2 3 

hasil dari perkalian matrix
[[34, 28, 30], [31, 22, 25], [18, 12, 14]] 



## Cara Mengalikan Matrix Menggunakan Program Python Dengan Library Numpy


In [7]:
a = np.array([(5,3),
              (5,2),
              (3,1)])

b = np.array([(5,2,3),
              (3,6,5)])

hasil = np.dot(a,b)
print(hasil)

[[34 28 30]
 [31 22 25]
 [18 12 14]]
