# Materi & Tugas Pertemuan 3
## Menghitung matrix menggunakan Program
### Cara Menentukan Matrix Secara Random menggunakan progam python
1. kita memanggil numpy dan random menggunakan syntax 
[import numpy] & [import Random]
import gunanya untuk kita memanggil file lain dalam satu modul,
numpy dan random adalah sebuah library yang bisa di panggil 

2. kita membuat matrix menggunakan syntax
[ "A = numpy.random.randint(10, size=(3,3))" ]
Kita membuat Variabel "A", dengan isi "numpy.random.ranint(10, size=(3,0)),
disini kegunaan dari randint sendiri adalah untuk mengacak angka, dan 10 adalah batas dari acak angka randint, 
size=(3,3) adalah ukuran kolom baris sebuah matrix

### Cara menentukan Matrix Secara Manual Menggunakan Program python

1. kita memanggil library numpy menggunakan syntax
[import numpy]
import gunanya untuk kita memanggil file lain dalam satu modul,
numpy adalah sebuah library yang bisa di panggil 

2. kita membuat matrix secara manual menggunakan syntax
[ A = numpy.array([[3,0,4],[-1,-2,-1]]) ]
kita membuat variable "A", dengan isi numpy.array
numpy adalah library yang sudah kita panggil tadi, dan array kegunaannya untuk memudahkan operasi komputasi tipe data numerik seperti penjumlahan, pengurangan, perkalian, pangkat, dan operasi lainnya yang bisa diterapkan pada vektor atau matrix
dan kita memberi angka untuk kolom dan baris pada matrix

### Cara Mengubah matrix menjadi matrix transpose menggunakan program python
1. Menentukan Matrix mana yang ingin di transpose, dan beri syntax
[A.transpose()]
Syntax "transpose()" digunakan untuk menghasilkan transpos dari matriks A. Transpos suatu matriks adalah operasi yang mengubah baris matriks menjadi kolom dan sebaliknya. Dengan kata lain, elemen pada baris ke-i dan kolom ke-j dari matriks asli akan menjadi elemen pada baris ke-j dan kolom ke-i dalam matriks transpos.

### Cara Mengetahui Shape Matrix Menggunakan Program Python 
1. Menentukan variable matrix mana yang ingin di ketahui shape nya, dan tambahkan syntax
[A.Shape]
Shape digunakan untuk mendapatkan tuple yang menyatakan dimensi dari array/matriks A. Dalam konteks NumPy atau library lain yang mendukung atribut shape, A.shape memberikan informasi tentang jumlah baris dan kolom 

## TUGAS MATERI PERTEMUAN 3
Mengalikan Matrix Menggunakan Python

import numpy as np
import random

A = np.random.randint(10, size=(3, 3))
B = np.random.randint(10, size=(3, 3))
C = np.random.randint(10, size=(3, 3))
D = np.random.randint(10, size=(3, 3))

Hasil_awal = np.dot(A, B)
Hasil_awal = np.dot(Hasil_awal, C)
Hasil_akhir = np.dot(Hasil_awal, D)

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nMatrix C:")
print(C)
print("\nMatrix D:")
print(D)
print("\nHasil akhir perkalian matriks:")
print(Hasil_akhir)

In [1]:
# array ditentukan secara manual & Random
import numpy as np
import random

A = np.random.randint(10,size=(3,3))
B = np.array([[3,0,4],[-1,-2,-1]])
C = np.random.randint(10,size=(3,2))
D = np.array([[2],[6]])

print("Matrix A")
print(A,"\n")
print("Matrix B")
print(B,"\n")
print("Matrix C")
print(C,"\n")
print("Matrix D")
print(D,"\n")

Matrix A
[[9 1 4]
 [7 4 7]
 [0 1 1]] 

Matrix B
[[ 3  0  4]
 [-1 -2 -1]] 

Matrix C
[[8 6]
 [2 9]
 [1 4]] 

Matrix D
[[2]
 [6]] 



In [2]:
# operasi matrix

# C dan d adalah konnstanta
c = 2
d = 4
A1 = (c + d) * A
print(A1,"\n")
A2 = (c*A)+(d*A)
print(A2,"\n")

[[54  6 24]
 [42 24 42]
 [ 0  6  6]] 

[[54  6 24]
 [42 24 42]
 [ 0  6  6]] 



In [3]:
# Transpose matriks
A_T = A.transpose()
C_T = C.transpose()

In [4]:
# Lakukan perkalian matriks
TRANS = np.dot(C, C_T)

In [5]:
#Mengetahui Shape pada Matrix
C.shape

(3, 2)

In [6]:
# TUGAS MENGALIKAN MATRIX MENGGUNAKAN PROGRAM PYTHON

import numpy as np
import random

A = np.random.randint(10, size=(3, 3))
B = np.random.randint(10, size=(3, 3))
C = np.random.randint(10, size=(3, 3))
D = np.random.randint(10, size=(3, 3))

# Melakukan Pengalian Secara Bertahap
Hasil_awal = np.dot(A, B)
Hasil_awal = np.dot(Hasil_awal, C)
Hasil_akhir = np.dot(Hasil_awal, D)

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nMatrix C:")
print(C)
print("\nMatrix D:")
print(D)
print("\nHasil akhir perkalian matriks:")
print(Hasil_akhir)

Matrix A:
[[6 8 0]
 [2 8 7]
 [1 0 8]]

Matrix B:
[[4 0 7]
 [2 9 3]
 [6 5 5]]

Matrix C:
[[3 0 9]
 [3 3 6]
 [4 8 3]]

Matrix D:
[[8 0 2]
 [5 7 2]
 [3 9 8]]

Hasil akhir perkalian matriks:
[[11490 14118 10608]
 [15378 19430 15072]
 [ 8739 11113  8712]]
