# Materi & Tugas Pertemuan 2
## Menggambar Bidang 3 Dimensi
Eliminasi Gauss adalah algoritma yang digunakan untuk menyelesaikan sistem persamaan linear. Algoritma ini terdiri dari serangkaian operasi yang dilakukan pada matriks koefisien dari sistem persamaan tersebut.

Ada tiga jenis operasi baris dasar yang dapat dilakukan pada baris matriks tersebut:

1. Menukar posisi dua baris.

2. Mengalikan suatu baris dengan skalar bukan nol .

3. Menambahkan suatu baris dengan suatu kelipatan dari baris yang lain.

Operasi-operasi ini tidak mengubah kumpulan solusi. Oleh karena itu, jika tujuan seseorang adalah untuk menyelesaikan sistem persamaan linear, penggunaan operasi baris ini dapat membuat masalah menjadi lebih mudah

In [1]:
## Contoh penggunaan eliminasi gaussian pada bahasa pemrograman python
# import library numpy
import numpy as np
A=np.array([[8,9,1,19],[1,2,3,9],[2,1,1,5]])

In [2]:
def RowSwap(A,k,l):
# =============================================================================
#     A adalah sebuah NumPy array.  RowSwap akan menghasilkan duplicate dari 
#     array dengan baris k dan l di tukar
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A adalah sebuah NumPy array.  RowScale akan menghasilkan duplicate dari 
#     array dengan baris k di kali dengan skalar bukan 0
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A adalah sebuah NumPy array.  RowAddp akan menghasilkan duplicate dari 
#     array dengan baris k akan di kali dengan scalar bukan 0. lalu baris nilai
#     baris l akan di tambah dengan nilai baris k yang sudah dikalikan  
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [3]:
print(A,'\n')



[[ 8  9  1 19]
 [ 1  2  3  9]
 [ 2  1  1  5]] 



tukar posisi baris 1 dan baris 2

In [4]:
# 
A = RowSwap(A,0,1)
print(A,'\n')



[[ 1.  2.  3.  9.]
 [ 8.  9.  1. 19.]
 [ 2.  1.  1.  5.]] 



baris 1 di kali -8 lalu ditambahkan ke baris 2

In [5]:
# 
A1 = RowAdd(A,0,1,-8)
print(A1,'\n')



[[  1.   2.   3.   9.]
 [  0.  -7. -23. -53.]
 [  2.   1.   1.   5.]] 



baris 1 di kali -2 lalu ditambahkan ke baris 3

In [6]:
# 
A2 = RowAdd(A1,0,2,-2)
print(A2,'\n')



[[  1.   2.   3.   9.]
 [  0.  -7. -23. -53.]
 [  0.  -3.  -5. -13.]] 



baris 2 di kalikan dengan -1/7

In [7]:

A3 = RowScale(A2,1,-1/7)
print(A3,'\n')



[[  1.           2.           3.           9.        ]
 [ -0.           1.           3.28571429   7.57142857]
 [  0.          -3.          -5.         -13.        ]] 



baris 2 di kalikan 3 lalu ditambahkan ke baris 3

In [8]:

A4 = RowAdd(A3,1,2,3)
print(A4,'\n')



[[ 1.          2.          3.          9.        ]
 [-0.          1.          3.28571429  7.57142857]
 [ 0.          0.          4.85714286  9.71428571]] 



baris 3 di  kalikan dengan 1/4.85714286

In [9]:
A5 = RowScale(A4,2,1/4.85714286)
print(A5)

[[ 1.          2.          3.          9.        ]
 [-0.          1.          3.28571429  7.57142857]
 [ 0.          0.          1.          2.        ]]


In [10]:
print("Hasil x3, x2  dan x1")
x3 = 2
print('x3 =',x3)
x2 = 7.57142857 - 3.28571429 *2
print('x2 =',round(x2))
x1 = 9 - x2*2 - x3*3
print('x1 =', round(x1))

Hasil x3, x2  dan x1
x3 = 2
x2 = 1
x1 = 1


Hasil Dari Sistem Persamaan Berikut :

\begin{split}
    8x_1 + 9x_2 + x_3 = 19\\
    x_1  + 2x_2 + 3x_3 = 9\\
    2x_1 + x_2  + x_3 = 5
\end{split}

Hasil Setelah di bulatkan : 

\begin{split}
    x_1 + 2x_2 + 3x_3 = 9\\
    x_2 + 3x_3 = 8\\
    x_3 = 2
\end{split}
