# Matrix Invers
Dalam matematika, matriks invers adalah matriks yang ketika dikalikan dengan matriks aslinya menghasilkan matriks identitas.
Misal kita memiliki Matriks A, Jika ada sebuah matriks B sedemikian rupa, sehingga A x B = B x A = I, dimana I adalah Matriks Identitas, Maka B disebut Invers dari A, yang di lambangkan A-1,

## Mencari matrix invers menggunakan eliminasi gauss
Metode Gauss-Jordan merupakan salah satu varian dari eliminasi Gaussian yang dilakukan dengan cara operasi reduksi baris untuk mencari invers suatu matriks.

1 Misal kita mau mencari invers dari sebuah matriks 3x3
A = 

\begin{bmatrix}
1 & 2 & 3\\ 
0 & 1 & 4\\ 
5 & 6 & 0
\end{bmatrix}

I = 
\begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1\\
\end{bmatrix}

2.Setelah itu kita menggunakan eliminasi gaus jordan

\begin{bmatrix}
1 & 2 & 3 | 1 & 0 & 0\\
0 & 1 & 4 | 0 & 1 & 0\\
5 & 6 & 0 | 0 & 0 & 1\\
\end{bmatrix}

3.Sekarang kita kurangkan baris ketiga dengan 5x baris pertama

\begin{bmatrix}
1 & 2 & 3 | 1 & 0 & 0\\
0 & 1 & 4 | 0 & 1 & 0\\
0 & -4 & -15 | -5 & 0 & 1\\
\end{bmatrix}

4.Dari matriks diatas, kita tambahkan baris ke 3 dengan 4kali baris ke dua 

\begin{bmatrix}
1 & 2 & 3 | 1 & 0 & 0\\
0 & 1 & 4 | 0 & 1 & 0\\
0 & 0 & 1 | -5 & 4 & 1\\
\end{bmatrix}

5.Selanjutnya kita kurangkan baris kedua dengan 4x baris ketiga, dan kita kurangkan juga baris pertama dengan 3x baris ketiga

\begin{bmatrix}
1 & 2 & 0 | 16 & -12 & -3\\
0 & 1 & 0 | 20 & -15 & -4\\
0 & 0 & 1 | -5 & 4 & 1\\
\end{bmatrix}

6.langkah terakhir kita kurangkan baris pertama dengan 2x baris kedua

\begin{bmatrix}
1 & 0 & 0 | -24 & 18 & 5\\
0 & 1 & 0 | 20 & -15 & -4\\
0 & 0 & 1 | -5 & 4 & 1\\
\end{bmatrix}

Maka invers dari matriks A adalah : 

\begin{bmatrix}
-24 & 18 & 5\\
20 & -15 & -4\\
-5 & 4 & 1\\
\end{bmatrix}


## Program untuk Mencari matrix invers menggunakan eliminasi gauss

In [1]:
import numpy as np

# Membuat Matriks 
A = np.array([(1,2,3),
             (0,1,4),
             (5,6,0)])
I = np.array([(1,0,0),
              (0,1,0),
              (0,0,1)])
print("Matriks A : \n")
print(A)
print("\n Matriks Identitas : \n")
print(I)

Matriks A : 

[[1 2 3]
 [0 1 4]
 [5 6 0]]

 Matriks Identitas : 

[[1 0 0]
 [0 1 0]
 [0 0 1]]


## Gunakan eliminasi Gauss

In [2]:
EG = np.array([(1,2,3,1,0,0),
             (0,1,4,0,1,0),
             (5,6,0,0,0,1)])
print(EG)

[[1 2 3 1 0 0]
 [0 1 4 0 1 0]
 [5 6 0 0 0 1]]


## Menambahkan Fungsi RowAdd

In [3]:
def RowAdd(A,k,l,scale):
# =============================================================================
#     A adalah sebuah NumPy array.  RowAdd akan menghasilkan duplicate dari 
#     array dengan baris k akan di kali dengan 'scale' bukan 0. lalu nilai
#     baris l akan di tambah dengan nilai baris k yang sudah dikalikan  
# =============================================================================
    m = A.shape[0]  # m adalah nomor baris di A
    n = A.shape[1]  # n adalah nomor kolom di A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

def RowSwap(A,k,l):
# =============================================================================
#     A adalah sebuah NumPy array.  RowSwap akan menghasilkan duplicate dari 
#     array dengan baris k dan l di tukar
# =============================================================================
    m = A.shape[0]  # m adalah nomor baris di A
    n = A.shape[1]  # n adalah nomor kolom di A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A adalah sebuah NumPy array.  RowScale akan menghasilkan duplicate dari 
#     array dengan baris k di kali dengan skalar bukan 0
# =============================================================================
    m = A.shape[0]  # m adalah nomor baris di A
    n = A.shape[1]  # n adalah nomor kolom di A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

## Sekarang kita kurangkan baris ketiga dengan 5x baris pertama

In [4]:
RA = np.array([(1,2,3,1,0,0),
             (0,1,4,0,1,0),
             (5,6,0,0,0,1)])

k = 0
l = 2
scale = -5

result = RowAdd(RA, k, l, scale)
print("Matriks awal:")
print(RA)
print("\nHasil:")
print(result)

Matriks awal:
[[1 2 3 1 0 0]
 [0 1 4 0 1 0]
 [5 6 0 0 0 1]]

Hasil:
[[  1.   2.   3.   1.   0.   0.]
 [  0.   1.   4.   0.   1.   0.]
 [  0.  -4. -15.  -5.   0.   1.]]


## Dari matriks diatas, kita tambahkan baris ke 3 dengan 4kali baris ke dua

In [5]:
RA2 = np.array([(1,2,3,1,0,0),
             (0,1,4,0,1,0),
             (0,-4,-15,-5,0,1)])
k = 1
l = 2
scale = 4

result = RowAdd(RA2, k, l, scale)
print("Matriks awal:")
print(RA2)
print("\nHasil:")
print(result)

Matriks awal:
[[  1   2   3   1   0   0]
 [  0   1   4   0   1   0]
 [  0  -4 -15  -5   0   1]]

Hasil:
[[ 1.  2.  3.  1.  0.  0.]
 [ 0.  1.  4.  0.  1.  0.]
 [ 0.  0.  1. -5.  4.  1.]]


## selanjutnya kita kurangkan baris kedua dengan 4x baris ketiga,

In [6]:
RA3 = np.array([(1,2,3,1,0,0),
             (0,1,4,0,1,0),
             (0,0,1,-5,4,1)])

k = 2
l = 1
scale = -4

result = RowAdd(RA3, k, l, scale)
print("Matriks awal:")
print(RA3)
print("\nHasil :")
print(result)

Matriks awal:
[[ 1  2  3  1  0  0]
 [ 0  1  4  0  1  0]
 [ 0  0  1 -5  4  1]]

Hasil :
[[  1.   2.   3.   1.   0.   0.]
 [  0.   1.   0.  20. -15.  -4.]
 [  0.   0.   1.  -5.   4.   1.]]


## kita kurangkan juga baris pertama dengan 3x baris ketiga

In [7]:
RA4 = np.array([(1,2,3,1,0,0),
             (0,1,0,20,-15,-4),
             (0,0,1,-5,4,1)])
k = 2
l = 0
scale = -3

result = RowAdd(RA4, k, l, scale)
print("Matriks awal:")
print(RA4)
print("\nHasil :")
print(result)


Matriks awal:
[[  1   2   3   1   0   0]
 [  0   1   0  20 -15  -4]
 [  0   0   1  -5   4   1]]

Hasil :
[[  1.   2.   0.  16. -12.  -3.]
 [  0.   1.   0.  20. -15.  -4.]
 [  0.   0.   1.  -5.   4.   1.]]


## langkah terakhir kita kurangkan baris pertama dengan 2x baris kedua

In [8]:
RA5 = np.array([(1,2,0,16,-12,-3),
             (0,1,0,20,-15,-4),
             (0,0,1,-5,4,1)])
k = 1
l = 0
scale = -2

result = RowAdd(RA5, k, l, scale)
print("Matriks awal:")
print(RA5)
print("\nHasil :")
print(result)

Matriks awal:
[[  1   2   0  16 -12  -3]
 [  0   1   0  20 -15  -4]
 [  0   0   1  -5   4   1]]

Hasil :
[[  1.   0.   0. -24.  18.   5.]
 [  0.   1.   0.  20. -15.  -4.]
 [  0.   0.   1.  -5.   4.   1.]]


Maka invers dari matriks A adalah : 
\begin{bmatrix}
-24 & 18 & 5\\
20 & -15 & -4\\
-5 & 4 & 1\\
\end{bmatrix}

## Penyelesaian sistem persamaan linear menggunakan matriks invers 
Buatkan Penyelesaian sistem persamaan dari :

$$
    2a + 3b + c + d = 12

    a + b + 5c — d = 15

    3a + 2b + 2c + 4d = 9

    4a — b + 3c + 2d = 5
$$
##### Matriks Sistem Persamaan linear 
$$
\begin{bmatrix}
2 & 3 & 1 & 1\\
1 & 1 & 5 & 1\\
3 & 2 & 2 & 4\\
4 & 1 & 3 & 2
\end{bmatrix}
\begin{bmatrix}
12\\
15\\
9\\
5
\end{bmatrix}
$$

In [9]:
import numpy as np
 
A = np.array([[2,3,1,1,1,0,0,0],
              [1,1,5,1,0,1,0,0],
              [3,2,2,4,0,0,1,0],
              [4,1,3,2,0,0,0,1]])
print(A)

[[2 3 1 1 1 0 0 0]
 [1 1 5 1 0 1 0 0]
 [3 2 2 4 0 0 1 0]
 [4 1 3 2 0 0 0 1]]


In [10]:
k = 1
l = 0
scale = -1

h = RowAdd(A, k, l, scale)
print("Matriks awal:")
print(A)
print("\nHasil :")
print(h)

Matriks awal:
[[2 3 1 1 1 0 0 0]
 [1 1 5 1 0 1 0 0]
 [3 2 2 4 0 0 1 0]
 [4 1 3 2 0 0 0 1]]

Hasil :
[[ 1.  2. -4.  0.  1. -1.  0.  0.]
 [ 1.  1.  5.  1.  0.  1.  0.  0.]
 [ 3.  2.  2.  4.  0.  0.  1.  0.]
 [ 4.  1.  3.  2.  0.  0.  0.  1.]]


In [11]:
k = 0
l = 1
scale = -1

h2 = RowAdd(h, k, l, scale)
print("Matriks awal:")
print(h)
print("\nHasil :")
print(h2)

Matriks awal:
[[ 1.  2. -4.  0.  1. -1.  0.  0.]
 [ 1.  1.  5.  1.  0.  1.  0.  0.]
 [ 3.  2.  2.  4.  0.  0.  1.  0.]
 [ 4.  1.  3.  2.  0.  0.  0.  1.]]

Hasil :
[[ 1.  2. -4.  0.  1. -1.  0.  0.]
 [ 0. -1.  9.  1. -1.  2.  0.  0.]
 [ 3.  2.  2.  4.  0.  0.  1.  0.]
 [ 4.  1.  3.  2.  0.  0.  0.  1.]]


In [12]:
k = 0
l = 2
scale = -3

h3 = RowAdd(h2, k, l, scale)
print("Matriks awal:")
print(h2)
print("\nHasil :")
print(h3)

Matriks awal:
[[ 1.  2. -4.  0.  1. -1.  0.  0.]
 [ 0. -1.  9.  1. -1.  2.  0.  0.]
 [ 3.  2.  2.  4.  0.  0.  1.  0.]
 [ 4.  1.  3.  2.  0.  0.  0.  1.]]

Hasil :
[[ 1.  2. -4.  0.  1. -1.  0.  0.]
 [ 0. -1.  9.  1. -1.  2.  0.  0.]
 [ 0. -4. 14.  4. -3.  3.  1.  0.]
 [ 4.  1.  3.  2.  0.  0.  0.  1.]]


In [13]:
k = 0
l = 3
scale = -4

h4 = RowAdd(h3, k, l, scale)
print("Matriks awal:")
print(h3)
print("\nHasil :")
print(h4)

Matriks awal:
[[ 1.  2. -4.  0.  1. -1.  0.  0.]
 [ 0. -1.  9.  1. -1.  2.  0.  0.]
 [ 0. -4. 14.  4. -3.  3.  1.  0.]
 [ 4.  1.  3.  2.  0.  0.  0.  1.]]

Hasil :
[[ 1.  2. -4.  0.  1. -1.  0.  0.]
 [ 0. -1.  9.  1. -1.  2.  0.  0.]
 [ 0. -4. 14.  4. -3.  3.  1.  0.]
 [ 0. -7. 19.  2. -4.  4.  0.  1.]]


In [14]:
k = 1
l = 0
scale = -1

h5 = RowScale(h4, k, scale)
print("Matriks awal:")
print(h4)
print("\nHasil :")
print(h5)

Matriks awal:
[[ 1.  2. -4.  0.  1. -1.  0.  0.]
 [ 0. -1.  9.  1. -1.  2.  0.  0.]
 [ 0. -4. 14.  4. -3.  3.  1.  0.]
 [ 0. -7. 19.  2. -4.  4.  0.  1.]]

Hasil :
[[ 1.  2. -4.  0.  1. -1.  0.  0.]
 [-0.  1. -9. -1.  1. -2. -0. -0.]
 [ 0. -4. 14.  4. -3.  3.  1.  0.]
 [ 0. -7. 19.  2. -4.  4.  0.  1.]]


In [15]:
k = 1
l = 0
scale = -2

h6 = RowAdd(h5, k, l, scale)
print("Matriks awal:")
print(h5)
print("\nHasil :")
print(h6)

Matriks awal:
[[ 1.  2. -4.  0.  1. -1.  0.  0.]
 [-0.  1. -9. -1.  1. -2. -0. -0.]
 [ 0. -4. 14.  4. -3.  3.  1.  0.]
 [ 0. -7. 19.  2. -4.  4.  0.  1.]]

Hasil :
[[ 1.  0. 14.  2. -1.  3.  0.  0.]
 [-0.  1. -9. -1.  1. -2. -0. -0.]
 [ 0. -4. 14.  4. -3.  3.  1.  0.]
 [ 0. -7. 19.  2. -4.  4.  0.  1.]]


In [16]:
k = 1
l = 2
scale = 4

h7 = RowAdd(h6, k, l, scale)
print("Matriks awal:")
print(h6)
print("\nHasil :")
print(h7)

Matriks awal:
[[ 1.  0. 14.  2. -1.  3.  0.  0.]
 [-0.  1. -9. -1.  1. -2. -0. -0.]
 [ 0. -4. 14.  4. -3.  3.  1.  0.]
 [ 0. -7. 19.  2. -4.  4.  0.  1.]]

Hasil :
[[  1.   0.  14.   2.  -1.   3.   0.   0.]
 [ -0.   1.  -9.  -1.   1.  -2.  -0.  -0.]
 [  0.   0. -22.   0.   1.  -5.   1.   0.]
 [  0.  -7.  19.   2.  -4.   4.   0.   1.]]


In [17]:
k = 1
l = 3
scale = 7
h8 = RowAdd(h7, k, l, scale)
print("Matriks awal:")
print(h7)
print("\nHasil :")
print(h8)

Matriks awal:
[[  1.   0.  14.   2.  -1.   3.   0.   0.]
 [ -0.   1.  -9.  -1.   1.  -2.  -0.  -0.]
 [  0.   0. -22.   0.   1.  -5.   1.   0.]
 [  0.  -7.  19.   2.  -4.   4.   0.   1.]]

Hasil :
[[  1.   0.  14.   2.  -1.   3.   0.   0.]
 [ -0.   1.  -9.  -1.   1.  -2.  -0.  -0.]
 [  0.   0. -22.   0.   1.  -5.   1.   0.]
 [  0.   0. -44.  -5.   3. -10.   0.   1.]]


In [18]:
k = 2
l = 2
scale = -1/22

h9 = RowScale(h8, k, scale)
print("Matriks awal:")
print(h8)
print("\nHasil :")
print(h9)

Matriks awal:
[[  1.   0.  14.   2.  -1.   3.   0.   0.]
 [ -0.   1.  -9.  -1.   1.  -2.  -0.  -0.]
 [  0.   0. -22.   0.   1.  -5.   1.   0.]
 [  0.   0. -44.  -5.   3. -10.   0.   1.]]

Hasil :
[[  1.           0.          14.           2.          -1.
    3.           0.           0.        ]
 [ -0.           1.          -9.          -1.           1.
   -2.          -0.          -0.        ]
 [ -0.          -0.           1.          -0.          -0.04545455
    0.22727273  -0.04545455  -0.        ]
 [  0.           0.         -44.          -5.           3.
  -10.           0.           1.        ]]


In [19]:
k = 2
l = 0
scale = -14

h10 = RowAdd(h9, k, l,scale)
print("Matriks awal:")
print(h9)
print("\nHasil :")
print(h10)

Matriks awal:
[[  1.           0.          14.           2.          -1.
    3.           0.           0.        ]
 [ -0.           1.          -9.          -1.           1.
   -2.          -0.          -0.        ]
 [ -0.          -0.           1.          -0.          -0.04545455
    0.22727273  -0.04545455  -0.        ]
 [  0.           0.         -44.          -5.           3.
  -10.           0.           1.        ]]

Hasil :
[[  1.           0.           0.           2.          -0.36363636
   -0.18181818   0.63636364   0.        ]
 [ -0.           1.          -9.          -1.           1.
   -2.          -0.          -0.        ]
 [ -0.          -0.           1.          -0.          -0.04545455
    0.22727273  -0.04545455  -0.        ]
 [  0.           0.         -44.          -5.           3.
  -10.           0.           1.        ]]


In [20]:
k = 2
l = 1
scale = 9

h11 = RowAdd(h10, k, l,scale)
print("Matriks awal:")
print(h10)
print("\nHasil :")
print(h11)

Matriks awal:
[[  1.           0.           0.           2.          -0.36363636
   -0.18181818   0.63636364   0.        ]
 [ -0.           1.          -9.          -1.           1.
   -2.          -0.          -0.        ]
 [ -0.          -0.           1.          -0.          -0.04545455
    0.22727273  -0.04545455  -0.        ]
 [  0.           0.         -44.          -5.           3.
  -10.           0.           1.        ]]

Hasil :
[[  1.           0.           0.           2.          -0.36363636
   -0.18181818   0.63636364   0.        ]
 [ -0.           1.           0.          -1.           0.59090909
    0.04545455  -0.40909091  -0.        ]
 [ -0.          -0.           1.          -0.          -0.04545455
    0.22727273  -0.04545455  -0.        ]
 [  0.           0.         -44.          -5.           3.
  -10.           0.           1.        ]]


In [21]:
k = 2
l = 3
scale = 44

h12 = RowAdd(h11, k, l,scale)
print("Matriks awal:")
print(h11)
print("\nHasil :")
print(h12)

Matriks awal:
[[  1.           0.           0.           2.          -0.36363636
   -0.18181818   0.63636364   0.        ]
 [ -0.           1.           0.          -1.           0.59090909
    0.04545455  -0.40909091  -0.        ]
 [ -0.          -0.           1.          -0.          -0.04545455
    0.22727273  -0.04545455  -0.        ]
 [  0.           0.         -44.          -5.           3.
  -10.           0.           1.        ]]

Hasil :
[[ 1.          0.          0.          2.         -0.36363636 -0.18181818
   0.63636364  0.        ]
 [-0.          1.          0.         -1.          0.59090909  0.04545455
  -0.40909091 -0.        ]
 [-0.         -0.          1.         -0.         -0.04545455  0.22727273
  -0.04545455 -0.        ]
 [ 0.          0.          0.         -5.          1.          0.
  -2.          1.        ]]


In [22]:
k = 3
l = 3
scale = -1/5

h13 = RowScale(h12, k,scale)
print("Matriks awal:")
print(h12)
print("\nHasil :")
print(h13)

Matriks awal:
[[ 1.          0.          0.          2.         -0.36363636 -0.18181818
   0.63636364  0.        ]
 [-0.          1.          0.         -1.          0.59090909  0.04545455
  -0.40909091 -0.        ]
 [-0.         -0.          1.         -0.         -0.04545455  0.22727273
  -0.04545455 -0.        ]
 [ 0.          0.          0.         -5.          1.          0.
  -2.          1.        ]]

Hasil :
[[ 1.          0.          0.          2.         -0.36363636 -0.18181818
   0.63636364  0.        ]
 [-0.          1.          0.         -1.          0.59090909  0.04545455
  -0.40909091 -0.        ]
 [-0.         -0.          1.         -0.         -0.04545455  0.22727273
  -0.04545455 -0.        ]
 [-0.         -0.         -0.          1.         -0.2        -0.
   0.4        -0.2       ]]


In [23]:
k = 3
l = 0
scale = -2

h14 = RowAdd(h13, k, l, scale)
print("Matriks awal:")
print(h13)
print("\nHasil :")
print(h14)

Matriks awal:
[[ 1.          0.          0.          2.         -0.36363636 -0.18181818
   0.63636364  0.        ]
 [-0.          1.          0.         -1.          0.59090909  0.04545455
  -0.40909091 -0.        ]
 [-0.         -0.          1.         -0.         -0.04545455  0.22727273
  -0.04545455 -0.        ]
 [-0.         -0.         -0.          1.         -0.2        -0.
   0.4        -0.2       ]]

Hasil :
[[ 1.          0.          0.          0.          0.03636364 -0.18181818
  -0.16363636  0.4       ]
 [-0.          1.          0.         -1.          0.59090909  0.04545455
  -0.40909091 -0.        ]
 [-0.         -0.          1.         -0.         -0.04545455  0.22727273
  -0.04545455 -0.        ]
 [-0.         -0.         -0.          1.         -0.2        -0.
   0.4        -0.2       ]]


In [24]:
k = 3
l = 1
scale = 1

h15 = RowAdd(h14, k, l, scale)
print("Matriks awal:")
print(h14)
print("\nHasil :")
print(h15)

Matriks awal:
[[ 1.          0.          0.          0.          0.03636364 -0.18181818
  -0.16363636  0.4       ]
 [-0.          1.          0.         -1.          0.59090909  0.04545455
  -0.40909091 -0.        ]
 [-0.         -0.          1.         -0.         -0.04545455  0.22727273
  -0.04545455 -0.        ]
 [-0.         -0.         -0.          1.         -0.2        -0.
   0.4        -0.2       ]]

Hasil :
[[ 1.          0.          0.          0.          0.03636364 -0.18181818
  -0.16363636  0.4       ]
 [-0.          1.          0.          0.          0.39090909  0.04545455
  -0.00909091 -0.2       ]
 [-0.         -0.          1.         -0.         -0.04545455  0.22727273
  -0.04545455 -0.        ]
 [-0.         -0.         -0.          1.         -0.2        -0.
   0.4        -0.2       ]]


In [25]:
Inv = np.array([[0.03636364, -0.18181818,  -0.16363636,  0.4],
            [0.39090909,  0.04545455,  -0.00909091, -0.2       ],
            [-0.04545455,  0.22727273,  -0.04545455, -0        ],
            [ -0.2,        -0,   0.4,        -0.2,       ]])
B = np.array([[12],
              [15],
               [9],
               [5]])

hasil = np.dot(Inv,B)
print(hasil)


[[-1.76363626]
 [ 4.29090914]
 [ 2.4545454 ]
 [ 0.2       ]]


import numpy as np
 
A = np.array([[2,3,1,1,1,0,0,0],
              [1,1,5,1,0,1,0,0],
              [3,2,2,4,0,0,1,0],
              [4,1,3,2,0,0,0,1]])
print(A)

In [26]:
A1 = A[0,:-4]
per1 = A1@hasil
print(per1)

[12.0000003]


In [27]:
A2 = A[1,:-4]
per2 = A2@hasil
print(per2)

[14.99999988]


In [28]:
A3 = A[2,:-4]
per3 = A3@hasil
print(per3)

[9.0000003]


In [29]:
A4 = A[3,:-4]
per4 = A4@hasil
print(per4)

[5.0000003]
