# Matrix Invers
Dalam matematika, matriks invers adalah matriks yang ketika dikalikan dengan matriks aslinya menghasilkan matriks identitas.
Misal kita memiliki Matriks A, Jika ada sebuah matriks B sedemikian rupa, sehingga A x B = B x A = I, dimana I adalah Matriks Identitas, Maka B disebut Invers dari A, yang di lambangkan A-1,

## Mencari matrix invers menggunakan eliminasi gauss
Metode Gauss-Jordan merupakan salah satu varian dari eliminasi Gaussian yang dilakukan dengan cara operasi reduksi baris untuk mencari invers suatu matriks.

Misal kita mau mencari invers dari sebuah matriks 3x3
A = 
$$
\begin{bmatrix}
1 & 2 & 3\\ 
0 & 1 & 4\\ 
5 & 6 & 0
\end{bmatrix}
$$
$$
I = 
\begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1\\
\end{bmatrix}
$$
Setelah itu kita menggunakan eliminasi gaus jordan
$$
\begin{bmatrix}
1 & 2 & 3 | 1 & 0 & 0\\
0 & 1 & 4 | 0 & 1 & 0\\
5 & 6 & 0 | 0 & 0 & 1\\
\end{bmatrix}
$$ 
Sekarang kita kurangkan baris ketiga dengan 5x baris pertama
$$
\begin{bmatrix}
1 & 2 & 3 | 1 & 0 & 0\\
0 & 1 & 4 | 0 & 1 & 0\\
0 & -4 & -15 | -5 & 0 & 1\\
\end{bmatrix}
$$
Dari matriks diatas, kita tambahkan baris ke 3 dengan 4kali baris ke dua 
$$
\begin{bmatrix}
1 & 2 & 3 | 1 & 0 & 0\\
0 & 1 & 4 | 0 & 1 & 0\\
0 & 0 & 1 | -5 & 4 & 1\\
\end{bmatrix}
$$
selanjutnya kita kurangkan baris kedua dengan 4x baris ketiga, dan kita kurangkan juga baris pertama dengan 3x baris ketiga
$$
\begin{bmatrix}
1 & 2 & 0 | 16 & -12 & -3\\
0 & 1 & 0 | 20 & -15 & -4\\
0 & 0 & 1 | -5 & 4 & 1\\
\end{bmatrix}
$$
langkah terakhir kita kurangkan baris pertama dengan 2x baris kedua
$$
\begin{bmatrix}
1 & 0 & 0 | -24 & 18 & 5\\
0 & 1 & 0 | 20 & -15 & -4\\
0 & 0 & 1 | -5 & 4 & 1\\
\end{bmatrix}
$$
Maka invers dari matriks A adalah : 
$$
\begin{bmatrix}
-24 & 18 & 5\\
20 & -15 & -4\\
-5 & 4 & 1\\
\end{bmatrix}
$$

## Program untuk Mencari matrix invers menggunakan eliminasi gauss

In [2]:
import numpy as np

# Membuat Matriks 
A = np.array([(1,2,3),
             (0,1,4),
             (5,6,0)])
I = np.array([(1,0,0),
              (0,1,0),
              (0,0,1)])
print("Matriks A : \n")
print(A)
print("\n Matriks Identitas : \n")
print(I)

Matriks A : 

[[1 2 3]
 [0 1 4]
 [5 6 0]]

 Matriks Identitas : 

[[1 0 0]
 [0 1 0]
 [0 0 1]]


## Gunakan eliminasi Gauss

In [ ]:
EG = np.array([(1,2,3,1,0,0),
             (0,1,4,0,1,0),
             (5,6,0,0,0,1)])
print(EG)

## Menambahkan Fungsi RowAdd

In [4]:
def RowAdd(A,k,l,scale):
# =============================================================================
#     A adalah sebuah NumPy array.  RowAdd akan menghasilkan duplicate dari 
#     array dengan baris k akan di kali dengan 'scale' bukan 0. lalu nilai
#     baris l akan di tambah dengan nilai baris k yang sudah dikalikan  
# =============================================================================
    m = A.shape[0]  # m adalah nomor baris di A
    n = A.shape[1]  # n adalah nomor kolom di A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

def RowSwap(A,k,l):
# =============================================================================
#     A adalah sebuah NumPy array.  RowSwap akan menghasilkan duplicate dari 
#     array dengan baris k dan l di tukar
# =============================================================================
    m = A.shape[0]  # m adalah nomor baris di A
    n = A.shape[1]  # n adalah nomor kolom di A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A adalah sebuah NumPy array.  RowScale akan menghasilkan duplicate dari 
#     array dengan baris k di kali dengan skalar bukan 0
# =============================================================================
    m = A.shape[0]  # m adalah nomor baris di A
    n = A.shape[1]  # n adalah nomor kolom di A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

## Sekarang kita kurangkan baris ketiga dengan 5x baris pertama

In [14]:
RA = np.array([(1,2,3,1,0,0),
             (0,1,4,0,1,0),
             (5,6,0,0,0,1)])

k = 0
l = 2
scale = -5

result = RowAdd(RA, k, l, scale)
print("Matriks awal:")
print(RA)
print("\nHasil:")
print(result)

Matriks awal:
[[1 2 3 1 0 0]
 [0 1 4 0 1 0]
 [5 6 0 0 0 1]]

Matriks setelah baris ketiga dikurang dengan 5x baris pertama:
[[  1.   2.   3.   1.   0.   0.]
 [  0.   1.   4.   0.   1.   0.]
 [  0.  -4. -15.  -5.   0.   1.]]


## Dari matriks diatas, kita tambahkan baris ke 3 dengan 4kali baris ke dua

In [18]:
RA2 = np.array([(1,2,3,1,0,0),
             (0,1,4,0,1,0),
             (0,-4,-15,-5,0,1)])
k = 1
l = 2
scale = 4

result = RowAdd(RA2, k, l, scale)
print("Matriks awal:")
print(RA2)
print("\nHasil:")
print(result)

Matriks awal:
[[  1   2   3   1   0   0]
 [  0   1   4   0   1   0]
 [  0  -4 -15  -5   0   1]]

Matriks setelah baris ketiga dikurang dengan 5x baris pertama:
[[ 1.  2.  3.  1.  0.  0.]
 [ 0.  1.  4.  0.  1.  0.]
 [ 0.  0.  1. -5.  4.  1.]]


## selanjutnya kita kurangkan baris kedua dengan 4x baris ketiga,

In [21]:
RA3 = np.array([(1,2,3,1,0,0),
             (0,1,4,0,1,0),
             (0,0,1,-5,4,1)])

k = 2
l = 1
scale = -4

result = RowAdd(RA3, k, l, scale)
print("Matriks awal:")
print(RA3)
print("\nHasil :")
print(result)

Matriks awal:
[[ 1  2  3  1  0  0]
 [ 0  1  4  0  1  0]
 [ 0  0  1 -5  4  1]]

Matriks setelah baris ketiga dikurang dengan 5x baris pertama:
[[  1.   2.   3.   1.   0.   0.]
 [  0.   1.   0.  20. -15.  -4.]
 [  0.   0.   1.  -5.   4.   1.]]


## kita kurangkan juga baris pertama dengan 3x baris ketiga

In [22]:
RA4 = np.array([(1,2,3,1,0,0),
             (0,1,0,20,-15,-4),
             (0,0,1,-5,4,1)])
k = 2
l = 0
scale = -3

result = RowAdd(RA4, k, l, scale)
print("Matriks awal:")
print(RA4)
print("\nHasil :")
print(result)


Matriks awal:
[[  1   2   3   1   0   0]
 [  0   1   0  20 -15  -4]
 [  0   0   1  -5   4   1]]

Hasil :
[[  1.   2.   0.  16. -12.  -3.]
 [  0.   1.   0.  20. -15.  -4.]
 [  0.   0.   1.  -5.   4.   1.]]


## langkah terakhir kita kurangkan baris pertama dengan 2x baris kedua

In [24]:
RA5 = np.array([(1,2,0,16,-12,-3),
             (0,1,0,20,-15,-4),
             (0,0,1,-5,4,1)])
k = 1
l = 0
scale = -2

result = RowAdd(RA5, k, l, scale)
print("Matriks awal:")
print(RA5)
print("\nHasil :")
print(result)

Matriks awal:
[[  1   2   0  16 -12  -3]
 [  0   1   0  20 -15  -4]
 [  0   0   1  -5   4   1]]

Hasil :
[[  1.   0.   0. -24.  18.   5.]
 [  0.   1.   0.  20. -15.  -4.]
 [  0.   0.   1.  -5.   4.   1.]]


Maka invers dari matriks A adalah : 
\begin{bmatrix}
-24 & 18 & 5\\
20 & -15 & -4\\
-5 & 4 & 1\\
\end{bmatrix}

## Penyelesaian sistem persamaan linear menggunakan matriks invers 
Buatkan Penyelesaian sistem persamaan dari 
\begin{bmatrix}
4 & 8 & 5 & 4\\
4 & 5 & 4 & 5\\
5 & 4 & 1 & 6\\
3 & 5 & 2 & 4\\
\end{bmatrix}
menggunakan mantriks invers

#### Jawaban :

In [66]:
A = np.array([(4,8,5,4),
              (4,5,4,5),
              (5,4,1,6),
              (3,5,2,4)])
I = np.array([(1,0,0,0),
              (0,1,0,0),
              (0,0,1,0),
              (0,0,0,1)])
print("Matriks A : \n")
print(A)
print("\n Matriks identitas:")
print(I)
    

Matriks A : 

[[1 2 3 4]
 [2 1 0 3]
 [3 0 1 2]
 [4 3 2 1]]

 Matriks identitas:
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [13]:
A_E =np.array([(1,2,2,4,1,0,0,0),
              (2,6,4,0,0,1,0,0),
              (0,4,2,4,0,0,1,0),
              (2,4,4,3,0,0,0,1)])
print(A_E)

[[1 2 2 4 1 0 0 0]
 [2 6 4 0 0 1 0 0]
 [0 4 2 4 0 0 1 0]
 [2 4 4 3 0 0 0 1]]


In [7]:
A_1 =np.array([(1,2,2,4,1,0,0,0),
              (2,6,4,0,0,1,0,0),
              (0,4,2,4,0,0,1,0),
              (2,4,4,3,0,0,0,1)])

k = 0
l = 1
scale = -2

h = RowAdd(A_1, k, l, scale)
print("Matriks awal:")
print(A_1)
print("\nHasil :")
print(h)

Matriks awal:
[[1 2 2 4 1 0 0 0]
 [2 6 4 0 0 1 0 0]
 [0 4 2 4 0 0 1 0]
 [2 4 4 3 0 0 0 1]]

Hasil :
[[ 1.  2.  2.  4.  1.  0.  0.  0.]
 [ 0.  2.  0. -8. -2.  1.  0.  0.]
 [ 0.  4.  2.  4.  0.  0.  1.  0.]
 [ 2.  4.  4.  3.  0.  0.  0.  1.]]


In [19]:
k = 0
l = 3
scale = -2

result2 = RowAdd(result, k, l, scale)
print("Matriks awal:")
print(result)
print("\nHasil :")
print(result2)

Matriks awal:
[[ 1.  2.  2.  4.  1.  0.  0.  0.]
 [ 0.  2.  0. -8. -2.  1.  0.  0.]
 [ 0. -4. -2. -4.  0.  0. -1.  0.]
 [ 0.  0.  0. -5. -2.  0.  0.  1.]]

Hasil :
[[  1.   2.   2.   4.   1.   0.   0.   0.]
 [  0.   2.   0.  -8.  -2.   1.   0.   0.]
 [  0.  -4.  -2.  -4.   0.   0.  -1.   0.]
 [ -2.  -4.  -4. -13.  -4.   0.   0.   1.]]


In [20]:
k = 2
l = 2
scale = -2

result3 = RowAdd(result2, k, l, scale)
print("Matriks awal:")
print(result2)
print("\nHasil :")
print(result3)

Matriks awal:
[[  1.   2.   2.   4.   1.   0.   0.   0.]
 [  0.   2.   0.  -8.  -2.   1.   0.   0.]
 [  0.  -4.  -2.  -4.   0.   0.  -1.   0.]
 [ -2.  -4.  -4. -13.  -4.   0.   0.   1.]]

Hasil :
[[  1.   2.   2.   4.   1.   0.   0.   0.]
 [  0.   2.   0.  -8.  -2.   1.   0.   0.]
 [  0.   4.   2.   4.   0.   0.   1.   0.]
 [ -2.  -4.  -4. -13.  -4.   0.   0.   1.]]


In [25]:
k = 0
l = 3
scale = 2

result4 = RowAdd(result3, k, l, scale)
print("Matriks awal:")
print(result3)
print("\nMatriks setelah RowScale:")
print(result4)

Matriks awal:
[[  1.   2.   2.   4.   1.   0.   0.   0.]
 [  0.   2.   0.  -8.  -2.   1.   0.   0.]
 [  0.   4.   2.   4.   0.   0.   1.   0.]
 [ -2.  -4.  -4. -13.  -4.   0.   0.   1.]]

Matriks setelah RowScale:
[[ 1.  2.  2.  4.  1.  0.  0.  0.]
 [ 0.  2.  0. -8. -2.  1.  0.  0.]
 [ 0.  4.  2.  4.  0.  0.  1.  0.]
 [ 0.  0.  0. -5. -2.  0.  0.  1.]]


In [26]:
k = 1
l = 1
scale = 1/2

result5 = RowScale(result4, k, scale)
print("Matriks awal:")
print(result4)
print("\nMatriks setelah RowScale:")
print(result5)

Matriks awal:
[[ 1.  2.  2.  4.  1.  0.  0.  0.]
 [ 0.  2.  0. -8. -2.  1.  0.  0.]
 [ 0.  4.  2.  4.  0.  0.  1.  0.]
 [ 0.  0.  0. -5. -2.  0.  0.  1.]]

Matriks setelah RowScale:
[[ 1.   2.   2.   4.   1.   0.   0.   0. ]
 [ 0.   1.   0.  -4.  -1.   0.5  0.   0. ]
 [ 0.   4.   2.   4.   0.   0.   1.   0. ]
 [ 0.   0.   0.  -5.  -2.   0.   0.   1. ]]


In [27]:
k = 1
l = 2
scale = -4

result6 = RowAdd(result5, k, l, scale)
print("Matriks awal:")
print(result5)
print("\nMatriks setelah RowScale:")
print(result6)

Matriks awal:
[[ 1.   2.   2.   4.   1.   0.   0.   0. ]
 [ 0.   1.   0.  -4.  -1.   0.5  0.   0. ]
 [ 0.   4.   2.   4.   0.   0.   1.   0. ]
 [ 0.   0.   0.  -5.  -2.   0.   0.   1. ]]

Matriks setelah RowScale:
[[ 1.   2.   2.   4.   1.   0.   0.   0. ]
 [ 0.   1.   0.  -4.  -1.   0.5  0.   0. ]
 [ 0.   0.   2.  20.   4.  -2.   1.   0. ]
 [ 0.   0.   0.  -5.  -2.   0.   0.   1. ]]


In [28]:
k = 2
l = 2
scale = 1/2

result7 = RowScale(result6, k, scale)
print("Matriks awal:")
print(result6)
print("\nMatriks setelah RowScale:")
print(result7)

Matriks awal:
[[ 1.   2.   2.   4.   1.   0.   0.   0. ]
 [ 0.   1.   0.  -4.  -1.   0.5  0.   0. ]
 [ 0.   0.   2.  20.   4.  -2.   1.   0. ]
 [ 0.   0.   0.  -5.  -2.   0.   0.   1. ]]

Matriks setelah RowScale:
[[ 1.   2.   2.   4.   1.   0.   0.   0. ]
 [ 0.   1.   0.  -4.  -1.   0.5  0.   0. ]
 [ 0.   0.   1.  10.   2.  -1.   0.5  0. ]
 [ 0.   0.   0.  -5.  -2.   0.   0.   1. ]]


In [31]:
k = 3
l = 3
scale = -1/5

result8 = RowScale(result7, k, scale)
print("Matriks awal:")
print(result7)
print("\nMatriks setelah RowScale:")
print(result8)

Matriks awal:
[[ 1.   2.   2.   4.   1.   0.   0.   0. ]
 [ 0.   1.   0.  -4.  -1.   0.5  0.   0. ]
 [ 0.   0.   1.  10.   2.  -1.   0.5  0. ]
 [ 0.   0.   0.  -5.  -2.   0.   0.   1. ]]

Matriks setelah RowScale:
[[ 1.   2.   2.   4.   1.   0.   0.   0. ]
 [ 0.   1.   0.  -4.  -1.   0.5  0.   0. ]
 [ 0.   0.   1.  10.   2.  -1.   0.5  0. ]
 [-0.  -0.  -0.   1.   0.4 -0.  -0.  -0.2]]


In [32]:
k = 3
l = 2
scale = -10

result9 = RowAdd(result8, k, l, scale)
print("Matriks awal:")
print(result8)
print("\nMatriks setelah RowScale:")
print(result9)

Matriks awal:
[[ 1.   2.   2.   4.   1.   0.   0.   0. ]
 [ 0.   1.   0.  -4.  -1.   0.5  0.   0. ]
 [ 0.   0.   1.  10.   2.  -1.   0.5  0. ]
 [-0.  -0.  -0.   1.   0.4 -0.  -0.  -0.2]]

Matriks setelah RowScale:
[[ 1.   2.   2.   4.   1.   0.   0.   0. ]
 [ 0.   1.   0.  -4.  -1.   0.5  0.   0. ]
 [ 0.   0.   1.   0.  -2.  -1.   0.5  2. ]
 [-0.  -0.  -0.   1.   0.4 -0.  -0.  -0.2]]


In [34]:
k = 3
l = 1
scale = 4

result10 = RowAdd(result9, k, l, scale)
print("Matriks awal:")
print(result9)
print("\nMatriks setelah RowScale:")
print(result10)

Matriks awal:
[[ 1.   2.   2.   4.   1.   0.   0.   0. ]
 [ 0.   1.   0.  -4.  -1.   0.5  0.   0. ]
 [ 0.   0.   1.   0.  -2.  -1.   0.5  2. ]
 [-0.  -0.  -0.   1.   0.4 -0.  -0.  -0.2]]

Matriks setelah RowScale:
[[ 1.   2.   2.   4.   1.   0.   0.   0. ]
 [ 0.   1.   0.   0.   0.6  0.5  0.  -0.8]
 [ 0.   0.   1.   0.  -2.  -1.   0.5  2. ]
 [-0.  -0.  -0.   1.   0.4 -0.  -0.  -0.2]]


In [35]:
k = 3
l = 0
scale = -4

result11 = RowAdd(result10, k, l, scale)
print("Matriks awal:")
print(result10)
print("\nMatriks setelah RowScale:")
print(result11)

Matriks awal:
[[ 1.   2.   2.   4.   1.   0.   0.   0. ]
 [ 0.   1.   0.   0.   0.6  0.5  0.  -0.8]
 [ 0.   0.   1.   0.  -2.  -1.   0.5  2. ]
 [-0.  -0.  -0.   1.   0.4 -0.  -0.  -0.2]]

Matriks setelah RowScale:
[[ 1.   2.   2.   0.  -0.6  0.   0.   0.8]
 [ 0.   1.   0.   0.   0.6  0.5  0.  -0.8]
 [ 0.   0.   1.   0.  -2.  -1.   0.5  2. ]
 [-0.  -0.  -0.   1.   0.4 -0.  -0.  -0.2]]


In [42]:
k = 2
l = 0
scale = -2

result12 = RowAdd(result11, k, l, scale)
print("Matriks awal:")
print(result11)
print("\nMatriks setelah RowScale:")
print(result12)

Matriks awal:
[[ 1.   2.   2.   0.  -0.6  0.   0.   0.8]
 [ 0.   1.   0.   0.   0.6  0.5  0.  -0.8]
 [ 0.   0.   1.   0.  -2.  -1.   0.5  2. ]
 [-0.  -0.  -0.   1.   0.4 -0.  -0.  -0.2]]

Matriks setelah RowScale:
[[ 1.   2.   0.   0.   3.4  2.  -1.  -3.2]
 [ 0.   1.   0.   0.   0.6  0.5  0.  -0.8]
 [ 0.   0.   1.   0.  -2.  -1.   0.5  2. ]
 [-0.  -0.  -0.   1.   0.4 -0.  -0.  -0.2]]


In [43]:
k = 1
l = 0
scale = -2

result13 = RowAdd(result12, k, l, scale)
print("Matriks awal:")
print(result12)
print("\nMatriks setelah RowScale:")
print(result13)

Matriks awal:
[[ 1.   2.   0.   0.   3.4  2.  -1.  -3.2]
 [ 0.   1.   0.   0.   0.6  0.5  0.  -0.8]
 [ 0.   0.   1.   0.  -2.  -1.   0.5  2. ]
 [-0.  -0.  -0.   1.   0.4 -0.  -0.  -0.2]]

Matriks setelah RowScale:
[[ 1.   0.   0.   0.   2.2  1.  -1.  -1.6]
 [ 0.   1.   0.   0.   0.6  0.5  0.  -0.8]
 [ 0.   0.   1.   0.  -2.  -1.   0.5  2. ]
 [-0.  -0.  -0.   1.   0.4 -0.  -0.  -0.2]]
